#How many times did you have to leave your VSCode to complete this? 3
#List all the sources you used to complete this task? 3 google 
#How long did it take to complete this task? 7 mins
---
- name: Ansible playbook M3
  hosts: poc_hosts 
  become: true 
  tasks:
  - name: Install httpd package 
    dnf:
      name: httpd
      state: latest
  - name: Start and enable httpd service 
    service:
      name: httpd
      enabled: true 
      state: started

  - name: Create a custom index.htm1 file 
    copy:
      dest: /var/www/html/index.html
      content: |
        debug: var={{inventory_hostname}}
        debug: var={{ansible_hostname}}