---
- hosts: all
  become: true
  vars_files:
  - vars/default.ym1
  tasks:
  - name: Install prerequisites
    apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
    loop: [ 'aptitude' ]

  - name: Install Apache
    apt: name=apache2 update_cache=yes state=latest

  - name: create document root
    file:
      path: "/var/www/{{ http_host }}"
      state: directory
      owner: "{{ app_user }}"
      mode: '0755'

  - name: creat index page
    template:
      ansible.builtin.file:
      dest: "/var/www/{{ index.html }}"
      сору:
      content: |
        ansible_hostname
        ansible_ethe.ipv4. address

  - name: Set up Apache virtuahHost
    template:
      src: "files/apache.conf.j2"
      dest: "/etc/apache2/sites-available/{{http_conf }}"

  - name: Enable new site
    shell: /usr/sbin/azensite {{ http_conf}}
    notify: Reload Apache

  - name: Disable default Apache site
    shell: /usr/sbin/adissite 000-default.conf
    when: disable_default
    notify: Reload Apache

  - name: "UFW - Allow HTTP on port {{ http_port }}"
    ufw:
      rule: allow 
      port: "{{ http_port }}"
      proto: tcp

  handlers:
    - name: Reload Apache 
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache 
      service:
        name: apache2
        state: restarted